name: GitHub-Profile-Summary-Cards

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        env:
          # Use your existing secret name here
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          username: CosmicMagnetar