name: System-Radar-Update

on:
  schedule:
    - cron: "0 * * * *" # Updates every hour for "Constant" data
  workflow_dispatch:   # Allows you to manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # CRITICAL: This fixes the 9-second failure
    name: Generate-Spiderweb

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.6.0
        env:
          # Use your existing METRICS_TOKEN here
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          username: CosmicMagnetar
          theme: aura_dark # Matches your neon aesthetic